### ISSUE TITLE
New component creates CSS file by default

### ISSUE THREAD

**Issue by mattcheah** [obenjiro/vscode-arrr#7] opened 2020-08-31 00:18 UTC
For projects that use SCSS or others, it would be nice for the extension to check the `angular.json` file and see what type of CSS file is being used, and create that type of file instead.

**Comment by ShPelles** [comment] 2020-08-31 06:52
Duplicate of #5

**Comment by obenjiro** [comment] 2020-08-31 06:55
Yep. It should be fixed by #5 so it you still can recreate it with v0.1.0 then send me you project structure `tree -L 2` and your angular.json file

**Comment by obenjiro** [comment] 2020-09-27 08:58
Should be fixed in v0.1.2 - plz give it a try

**Closed by obenjiro** 2020-09-27 08:58 UTC
Labels: need more info
